version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - '3000:3000'
    depends_on:
      - ws
    networks:
      - app-net 

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.admin
    ports:
      - '4000:4000'
    depends_on:
      - ws
    networks:
      - app-net 

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/products.json:/app/products.json
    networks:
      - app-net 
    

  ws:
    build:
      context: ./ws
      dockerfile: Dockerfile.ws
    ports:
      - '4050:4050'
    networks:
      - app-net 

  lb:
    image: nginx:stable-alpine
    container_name: lb
    ports:
      - "8080:80"            
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend              
    networks:
      - app-net   


networks:
  app-net:
    driver: bridge
